EXTRA_CFLAGS += -I$(src)/..
EXTRA_CFLAGS += -DKFSD

# TODO: why do these not work for the below warning test?
# (Tested 2006/5/30 on kudos-mm by Frost)
#GCC_VERSION := $(call cc-version)
#ifeq ($(shell echo $(GCC_VERSION) -ge 0304),0)
# The more appropriate "$(call cc-option,foo)" also does not work.
              


	#file_hiding_cfs.o \

GCC_VERSION := $(shell $(CONFIG_SHELL) $(srctree)/scripts/gcc-version.sh $(CC))
ifeq ($(shell [ $(GCC_VERSION) -ge 0304 ] && echo 1 || echo 0),1)
	EXTRA_CFLAGS += -Wno-declaration-after-statement
endif

kfsobjrel = ../obj/kernel
kfsobj = $(src)/$(kfsobjrel)

obj-m += kkfsd.o

KKFSD_LIB_OBJS := \
              assert.o \
              kdprintf.o \
              qsort.o \
              vector.o \
              hash_map.o \
              hash_set.o \
              kfs_feature.o \
              strtol.o \
              strings.o \
              svnrevtol.o \
              sleep.o

KKFSD_KFS_OBJS := \
              kfsd.o \
              kfsd_init.o \
              debug.o \
              kernel_serve.o \
              kernel_opgroup_ops.o \
              kernel_opgroup_scopes.o \
              bdesc.o \
              blockman.o \
              block_alloc.o \
              chdesc.o \
              chdesc_util.o \
              revision.o \
              modman.o \
              opgroup.o \
              devfs_cfs.o \
              mem_bd.o \
              linux_bd.o \
              md_bd.o \
              block_resizer_bd.o \
              partition_bd.o \
              pc_ptable.o \
              bsd_ptable.o \
              wt_cache_bd.o \
              wb_cache_bd.o \
              wb2_cache_bd.o \
              journal_bd.o \
              unlink_bd.o \
              loop_bd.o \
              josfs_base.o \
              ext2_base.o \
              ext2_super_wb.o \
              ufs_base.o \
              ufs_common.o \
              ufs_alloc_lastpos.o \
              ufs_alloc_linear.o \
              ufs_dirent_linear.o \
              ufs_super_wb.o \
              ufs_cg_wb.o \
              icase_cfs.o \
              opgroup_lfs.o \
              wholedisk_lfs.o \
              uhfs.o \
              sched.o \
              sync.o \
              destroy.o

kkfsd-objs := $(addprefix $(kfsobjrel)/,$(KKFSD_LIB_OBJS)) \
		$(addprefix $(kfsobjrel)/,$(KKFSD_KFS_OBJS))

$(addprefix $(kfsobj)/,$(KKFSD_LIB_OBJS)): $(kfsobj)/%.o : $(src)/../lib/%.c
	@test -d $(kfsobj)/kernel || mkdir -p $(kfsobj)/kernel
	$(call cmd,force_checksrc)
	$(call if_changed_rule,cc_o_c)

$(addprefix $(kfsobj)/,$(KKFSD_KFS_OBJS)): $(kfsobj)/%.o : $(src)/%.c
	@test -d $(kfsobj)/kernel || mkdir -p $(kfsobj)/kernel
	$(call cmd,force_checksrc)
	$(call if_changed_rule,cc_o_c)
