#ifndef __KUDOS_KFS_MAGIC_H
#define __KUDOS_KFS_MAGIC_H

/* "BDACCESS" */
#define DEVFS_MAGIC 0xBDACCE55

/* "FIDCLOSE" */
#define FIDCLOSER_MAGIC 0xF1DC105E

/* "FIDPROTR" */
#define FIDPROTECTOR_MAGIC 0xF1D78078

/* "JOSCFSMG" */
#define JOSFS_CFS_MAGIC 0x705CF535

/* use the same magic number for objects as in the FS */
#define JOSFS_MAGIC JOSFS_FS_MAGIC

/* "SAFEDATA" */
#define JOURNAL_MAGIC 0x5AFEDA7A

/* "???BDAID" */
#define MIRROR_BD_MAGIC 0x888BDA1D

/* "TBLCLASS" */
#define TABLE_CLASSIFIER_MAGIC 0x7B1C1A55

/* "FILEHIDE" */
#define FILE_HIDING_MAGIC 0xF11E41DE

/* "LEET0CFS" (because UHFS is leet) */
#define UHFS_MAGIC 0x1EE70CF5

/* "DATADELA" */
#define WB_CACHE_MAGIC 0xDA7ADE1A

/* "DISCORDR" */
#define ELEVATOR_CACHE_MAGIC 0xD15C08D8

/* "WOLEDISC" */
#define WHOLEDISK_MAGIC 0x301ED15C

#endif /* __KUDOS_KFS_MAGIC_H */
