#!/bin/bash

function usage () {
	echo "Usage; `basename "$0"` [-h] [-d TESTS_DIR]"
}

TESTS=tests-sosp-imap

while getopts "d:h\?" flag; do
	case "$flag" in
		d) TESTS="$OPTARG";;
		h|\?) usage; exit 0;;
		*) echo "Unknown argument \"$flag\"" 1>&2; usage 1>&2; exit 1;;
	esac
done

if [ ! -d $TESTS ]; then
	echo "No test directory $TESTS" 1>&2
	exit 1
fi

echo "# host diskcache fs cmode acmode wall_time sys_time write_reqs"
for dir in $TESTS/*; do
	echo -n "`cat $dir/host` "
	echo -n "`cat $dir/diskcache` "
	echo -n "`cat $dir/fs` "
	echo -n "`cat $dir/consistency_mode` "
	echo -n "`cat $dir/app_consistency_mode` "
	echo -n "`bench/ex_time -d $dir -t imap | awk '{print $1, $4}'` "
	if [ -n "`which blkparse`" ]; then
		bench/ex_io -d $dir -t imap | awk '{print $1}'
	else
		echo
	fi
done
