#!/bin/bash

if [ ! -d tests-sosp-memopt ]; then
	echo "No test directory tests-sosp-memopt" 1>&2
	exit 1
fi

echo "# patches(#) undo(kB) systime(sec)"
for TEST in tar rm postmark andrew; do
	echo $TEST
	for dir in tests-sosp-memopt/*; do
		echo -n "	`cat $dir/name`  "
		echo -n "`bench/ex_space -d $dir -t $TEST | awk '{print $19}'` "
		echo -n "`bench/ex_space -d $dir -t $TEST | awk '{print $29/1024}'` "
		bench/ex_time -d $dir -t $TEST-mem | awk '{print $4}'
	done
done
