#!/bin/bash

TESTS=${TESTS:-tests-sosp-patch}

if [ ! -d $TESTS ]; then
	echo "No test directory $TESTS" 1>&2
	exit 1
fi

echo "# patches(#) undo(kB) total(kB) systime(sec)"
for TEST in tar rm postmark andrew; do
	echo $TEST
	for dir in $TESTS/*; do
		echo -n "	`cat $dir/name`  "
		echo -n "`bench/ex_space -d $dir -t $TEST | awk '{print $19}'` "
		echo -n "`bench/ex_space -d $dir -t $TEST | awk '{print $29/1024}'` "
		echo -n "`bench/ex_space -d $dir -t $TEST | awk '{print $19*$20/1024 + $24*$25/1024 + $29/1024}'` "
		bench/ex_time -d $dir -t $TEST-mem | awk '{print $4}'
	done
done
