#!/bin/bash

BENCHDIR="`dirname "$0"`/.."
. $BENCHDIR/common
FSTITCHDIR="$BENCHDIR/.."

function run () {
	echo "## $1"
	try bench/new -n $1
	for TEST in tar_rm postmark andrew; do
		TESTNAME=mem try bench/multi 5 bench/$TEST
	done
}

function setmacro () {
	VAR=$1
	VAL=$2
	FILE=$3
	sed -i "s/^#define $VAR .$/#define $VAR $VAL/" $FILE
}

if [ $# -gt 0 ]; then
	echo "Usage: `basename "$0"`" 1>&2
	exit 1
fi

if [ -a tests ] ; then
	echo "Remove the tests/ directory and then run" 1>&2
	exit 1
fi
if [ -a tests-sosp-patch ]; then
	echo "Remove the tests-sosp-patch/ directory and then run" 1>&2
	exit 1
fi

accounting_on

setmacro PATCH_NRB 0 fscore/bdesc.h
setmacro PATCH_BYTE_MERGE_OVERLAP 0 fscore/patch.c
setmacro PATCH_BIT_MERGE_OVERLAP 0 fscore/patch.c
run NONE

setmacro PATCH_NRB 1 fscore/bdesc.h
run NRB

setmacro PATCH_NRB 0 fscore/bdesc.h
setmacro PATCH_BYTE_MERGE_OVERLAP 1 fscore/patch.c
setmacro PATCH_BIT_MERGE_OVERLAP 1 fscore/patch.c
run OVERLAP

setmacro PATCH_NRB 1 fscore/bdesc.h
run ALL

accounting_restore

mv tests tests-sosp-patch
