#!/bin/bash

function usage () {
	echo "Usage: `basename "$0"` [-h] [-d TESTS_DIR]"
}

TESTS=tests-sosp-patch

while getopts "d:h\?" flag; do
	case "$flag" in
		d) TESTS="$OPTARG";;
		h|\?) usage; exit 0;;
		*) echo "Unknown argument \"$flag\"" 1>&2; usage 1>&2; exit 1;;
	esac
done

if [ ! -d $TESTS ]; then
	echo "No test directory $TESTS" 1>&2
	exit 1
fi

echo "# patches(#) undo(MB) malloc(MB) blocks(MB) systime(sec)"
for TEST in tar rm postmark andrew; do
	echo $TEST
	for dir in $TESTS/*; do
		echo -n "	`cat $dir/name`  "
		echo -n "`bench/ex_space -d $dir -t $TEST | awk '{print $19}'` "
		echo -n "`bench/ex_space -d $dir -t $TEST | awk '{print $29/1024/1024}'` "
		# FIXME: average multiple runs
		echo -n "`grep 'malloc_total =' $dir/$TEST-mem.sys.0 | awk '{print $10/1024/1024}'` "
		echo -n "`grep 'malloc_blocks =' $dir/$TEST-mem.sys.0 | awk '{print $10/1024/1024}'` "
		bench/ex_time -d $dir -t $TEST-mem | awk '{print $4}'
	done
done
