#!/bin/bash

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/../common

RUNLINUX=0

function run () {
	[ $RUNLINUX -eq 0 ] && [ "$1" == "linux" ] && return
	[ $RUNLINUX -eq 1 ] && [ "$1" != "linux" ] && return
	try bench/new -h $1 -d $2 -f $3 -c $4
	for TEST in tar_rm postmark andrew; do
		try bench/multi 5 bench/$TEST
	done
}

if [ $# -eq 1 -a "$1" != "--linux" ] || [ $# -gt 1 ]; then
	echo "Usage: `basename "$0"` [--linux]" 1>&2
	exit 1
fi
if [ "$1" == "--linux" ]; then
	RUNLINUX=1
fi

if [ -a tests ] ; then
	echo "Remove the tests/ directory and then run" 1>&2
	exit 1
fi
if [ -a tests-sosp-time ]; then
	echo "Remove the tests-sosp-time/ directory and then run" 1>&2
	exit 1
fi

run kudos safe ext2 su opgroup
run kudos safe ext2 meta opgroup
run kudos safe ext2 full opgroup
run kudos unsafe ext2 none opgroup
run kudos unsafe ext2 full opgroup

run linux safe ext3 writeback fsync
run linux safe ext3 ordered fsync
run linux safe ext3 journal fsync
run linux unsafe ext2 none fsync
run linux unsafe ext3 journal fsync

mv tests tests-sosp-time
