#!/bin/bash

function usage () {
	echo "Usage: `basename "$0"` [-h] [-d TESTS_DIR]"
}

TESTS=tests-sosp-time

while getopts "d:h\?" flag; do
	case "$flag" in
		d) TESTS="$OPTARG";;
		h|\?) usage; exit 0;;
		*) echo "Unknown argument \"$flag\"" 1>&2; usage 1>&2; exit 1;;
	esac
done

if [ ! -d $TESTS ]; then
	echo "No test directory $TESTS" 1>&2
	exit 1
fi

echo "# host diskcache fs cmode acmode"
echo "#	wall_time sys_time"
for dir in $TESTS/*; do
	echo -n "`cat $dir/host` "
	echo -n "`cat $dir/diskcache` "
	echo -n "`cat $dir/fs` "
	cat $dir/consistency_mode
	for TEST in tar rm postmark andrew; do
		echo -n "	$TEST "
		bench/ex_time -d $dir -t $TEST | awk '{print $1, $4}'
	done
done
