#!/bin/bash

if [ ! -f .copy_to_kudos ]
then
	echo "No .copy_to_kudos file."
	echo -n "Please enter target directory: "
	read TARGET
	echo "$TARGET" > .copy_to_kudos
fi

TARGET="`cat .copy_to_kudos`"

function arg_error() {
	echo "Usage: `basename "$0"` <pb|mm>" 1>&2
	exit 1
}

if [ $# -ne 1 ]; then arg_error "$0"; fi

KMACHINE=kudos-$1.cs.ucla.edu
host $KMACHINE > /dev/null || arg_error "$0"

rsync --rsh=ssh -vaSz --exclude=/obj/ \
	--exclude=/.fdb_history \
	--exclude=/linux-2.6.15.tar \
	--exclude=/TAGS --exclude=/tags \
	--exclude=/time.log --exclude=/prof.log\
	--exclude=/test --exclude=/tests/ \
	--exclude=/core --exclude=/uufstitchd_debug \
	--exclude=/kfstitchd.ko --exclude=/kfstitchd.o \
	--exclude=/kfstitchd.mod.c --exclude=/kfstitchd.mod.o \
	--exclude=/Module.symvers --exclude=/.kfstitchd.*.cmd \
	--exclude=/.tmp_versions/ --exclude=/.kernel_version \
	--exclude=.*.swp --exclude=.*.swo --exclude=.*.swn \
	. $KMACHINE:$TARGET/
