ifeq ($(KERNELRELEASE),)
KERNELRELEASE = $(shell uname -r)
endif

ifeq ($(KERNELPATH),)
KERNELPATH = /lib/modules/${KERNELRELEASE}/build
endif

kfs/kkfsd.ko all: always
	$(MAKE) -C $(KERNELPATH) M=$(shell pwd) modules

install: kfs/kkfsd.ko
	$(MAKE) -C $(KERNELPATH) M=$(shell pwd) modules_install

clean:
	$(MAKE) -C $(KERNELPATH) M=$(shell pwd) clean

.PHONY: all always install clean
