#!/bin/bash

SIMPLIFY="`dirname "$0"`/patchdotsimplify"
DOT="`which -a dot | fgrep -v "$0" | head -n 1`"

if [ "${!#%.dot}" != "${!#}" ]
then
	P=()
	while [ $# -gt 1 ]
	do
		P[${#P}]="$1"
		shift
	done
	"$SIMPLIFY" < "$1" | "$DOT" "${P[@]}"
else
	"$SIMPLIFY" | "$DOT" "$@"
fi
