#!/bin/bash

SIMPLIFY=~/trunk/fsttich/util/patchdotsimplify
DOT="`which -a dot | tail +2 | head -n 1`"

if [ "${!#%.dot}" != "${!#}" ]
then
	P=()
	while [ $# -gt 1 ]
	do
		P[${#P}]="$1"
		shift
	done
	"$SIMPLIFY" < "$1" | "$DOT" "${P[@]}"
else
	"$SIMPLIFY" | "$DOT" "$@"
fi
