#!/bin/bash

OLDLINE=
function accounting_on () {
	OLDLINE="`grep '^#define CHDESC_ACCOUNT .$' $KUDOSDIR/kfs/chdesc.c`"
	if [ "$OLDLINE" != "#define CHDESC_ACCOUNT 1" ]; then
		sed -i "s/^#define CHDESC_ACCOUNT .\$/#define CHDESC_ACCOUNT 1/" $KUDOSDIR/kfs/chdesc.c
	fi
}
function accounting_restore () {
	if [ "$OLDLINE" != "#define CHDESC_ACCOUNT 1" ]; then
		sed -i "s/^#define CHDESC_ACCOUNT 1\$/$OLDLINE/" $KUDOSDIR/kfs/chdesc.c
		rm -f $KUDOSDIR/obj/*/chdesc.o $KUDOSDIR/obj/*/*/chdesc.o
	fi
}

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."
OUTDIR="$KUDOSDIR/test"
HOST="`cat $KUDOSDIR/test/host`"
FS="`cat $KUDOSDIR/test/fs`"

if [ $# -gt 1 ]; then
	echo "About: run all tests"
	echo "Usage: `basename "$0"` [NRUNS]" 1>&2
	exit 1;
fi
NRUNS=3
[ $# -eq 1 ] && NRUNS="$1"

$BENCHDIR/multi $NRUNS $BENCHDIR/tar_rm
if [ "$HOST" == "kudos" ] || [ "$HOST" == "uu" ]; then
	if grep -v linux- $OUTDIR/fs; then
		accounting_on; TESTNAME=mem $BENCHDIR/tar_rm; accounting_restore
	fi
fi

$BENCHDIR/multi $NRUNS $BENCHDIR/postmark
if [ "$HOST" == "kudos" ] || [ "$HOST" == "uu" ]; then
	if grep -v linux- $OUTDIR/fs; then
		accounting_on; TESTNAME=mem $BENCHDIR/postmark; accounting_restore
	fi
fi
