#!/bin/bash

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."
OUTDIR="$KUDOSDIR/test"
HOST="`cat $KUDOSDIR/test/host`"
FS="`cat $KUDOSDIR/test/fs`"

TESTS="tar_rm postmark andrew imap"

if [ $# -gt 1 ]; then
	echo "About: run all tests ($TESTS)"
	echo "Usage: `basename "$0"` [NRUNS]" 1>&2
	exit 1;
fi
NRUNS=3
[ $# -eq 1 ] && NRUNS="$1"

for TEST in $TESTS; do
	bench/single bench/$TEST $NRUNS
done
