#!/bin/bash

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
FSTITCHDIR="$BENCHDIR/.."
OUTDIR="$FSTITCHDIR/test"
load_config "$OUTDIR"
T=andrew
[ -n "$TESTNAME" ] && T="${T}-$TESTNAME"
N=`get_test_num $OUTDIR/$T`
MAB=ab-leiz.tar.gz

function test () {
	mkdir $MNT/workingdir
	ktime andrew sh -c "make -C $MNT/workingdir -f `pwd`/$FSTITCHDIR/obj/ab/original/Makefile >& $MNT/logfile"
	ktime sync fsync $FSTITCHDIR $MNT;
}

function run () {
	try $BENCHDIR/init -h $HOST -d $DISKCACHE -f $FS -c $CMODE $CRASHSIM -a start
	prepare_postinit  $T $N $OUTDIR $HOST
	ktime total test
	try $BENCHDIR/init -h $HOST -d $DISKCACHE -f $FS -c $CMODE $CRASHSIM -a stop
}

if [ $# -ne 0 ]; then
	echo "Usage: `basename "$0"`" 1>&2
	exit 1;
fi

# Set up the Modified Andrew Benchmark
mkdir -p $FSTITCHDIR/obj
rm -rf $FSTITCHDIR/obj/ab
tar C $FSTITCHDIR/obj -xzf $BENCHDIR/$MAB
rmdir $FSTITCHDIR/obj/ab/workingdir
sed -i "s,/home/leiz/ab/original,`pwd`/$FSTITCHDIR/obj/ab/original," $FSTITCHDIR/obj/ab/original/Makefile

build $T $N $FSTITCHDIR $HOST

log_kernel $T $N $OUTDIR $HOST
run 2>&1 | tee $OUTDIR/$T.run.$N
finish $T $N $FSTITCHDIR $OUTDIR $HOST $CRASHSIM
