#!/usr/bin/env perl

use File::Basename;
use Getopt::Std;

sub usage() {
	my $basename = basename($0);
	print STDERR "Usage: $basename [-h] <-d TEST_DIR> <-t TEST_NAME>\n";
	exit(1);
}

sub svnversion() {
	my $dir = $_[0];
	open(R, "<$dir/svnversion") || die;
	while(<R>) {
		my $line = $_;
		$line =~ m/(\d+).*/;
		my $rev = $1;
		close(R);
		return $rev;
	}
	close(R);
	die;
}

my %opt;

getopts("hd:t:", \%opt) or usage();
usage() if $opt{h} || !defined $opt{d} || !defined $opt{t};

if (!-d "$opt{d}") {
	print STDERR "Test output directory does not exist ($opt{d})\n";
	exit(1);
}

my $testdir = $opt{d};
my $testname = $opt{t};

if (!-f "$testdir/$testname-mem.sys.0") {
	print STDERR "No $testname-mem runs\n";
	exit(1);
}
my $rev = &svnversion($testdir);

sub createStat {
	return ("sum" => 0, "count" => 0, "min" => -1, "max" => 0);
}

sub createMeasurement {
	my %mean = createStat();
	my %max = createStat();
	my %total = createStat();
	my %total_realloc = createStat();
	return ("mean" => \%mean, "max" => \%max, "total" => \%total, "total_realloc" => \%total_realloc, "sizeof" => 0);
}

my %nbits = createMeasurement();
my %nbytes = createMeasurement();
my %nemptys = createMeasurement();
my %ntotal = createMeasurement();
my %ndeps = createMeasurement();
my %data = createMeasurement();

my %measurements = ("npatchs (bit)" => \%nbits, "npatchs (byte)" => \%nbytes, "npatchs (empty)" => \%nemptys, "npatchs (total)" => \%ntotal, "ndeps" => \%ndeps, "data" => \%data);
my @measurementsa = (\%nbits, \%nbytes, \%nemptys, \%ntotal, \%ndeps, \%data);

# update mean, max, or total
sub updateStat {
	my $stat = shift;
	my $n = shift;
	$stat->{"sum"} += $n;
	$stat->{"count"}++;
	$stat->{"min"} = $n if ($n < $stat->{"min"} || $stat->{"min"} == -1);
	$stat->{"max"} = $n if ($n > $stat->{"max"});
}

# update nbits, nbytes, etc
sub updateMeasurement {
	my $measurement = shift;
	my $mean = shift;
	my $max = shift;
	my $total = shift;
	my $total_realloc = shift;
	my $sizeof = shift;
	updateStat($measurement->{"mean"}, $mean);
	updateStat($measurement->{"max"}, $max);
	updateStat($measurement->{"total"}, $total);
	updateStat($measurement->{"total_realloc"}, $total_realloc);
	$measurement->{"sizeof"} = $sizeof;
}

%careabouts = ("npatchs (bit)" => 1, "npatchs (byte)" => 1, "npatchs (empty)" => 1, "npatchs (total)" => 1, "ndeps" => 1, "data" => 1);

foreach $run (<$testdir/$testname-mem.sys.*>) {
	open(R, "<$run") || die;
	while(<R>) {
		my $line = $_;
		if (! $line =~ m/account: /) {
			next;
		}
		if ($rev <= 3450) {
			$line =~ m/account: ([^:]+): mean=(\d+) max=(\d+) total=(\d+) sizeof=(\d+)/;
			updateMeasurement($measurements{"$1"}, $2, $3, $4, $4, $5) if (exists($careabouts{$1}));
		} else {
			$line =~ m/account: ([^:]+): mean=(\d+) max=(\d+) total=(\d+) total_realloc=(\d+) sizeof=(\d+)/;
			if ($rev == 3451 || $rev == 3452) {
				updateMeasurement($measurements{"$1"}, $2, $3, $5, $4, $6) if (exists($careabouts{$1}));
			} else {
				updateMeasurement($measurements{"$1"}, $2, $3, $4, $5, $6) if (exists($careabouts{$1}));
			}
		}
	}
	#print "\n";
	close(R);
}

sub averageStat {
	my $stat = shift;
	my $avg = 0;
	$avg = $stat->{"sum"} / $stat->{"count"} if ($stat->{"count"} != 0);
	return $avg;
}

foreach $measurement (@measurementsa) {
	foreach $stat ("mean", "max", "total", "total_realloc") {
		printf "%.2f ", averageStat($measurement->{$stat});
	}
	printf "%d  ", $measurement->{"sizeof"};
}
print "\n";
