#!/usr/bin/env perl

use File::Basename;
use Getopt::Std;

sub usage() {
	$basename = basename($0);
	print STDERR "Usage: $basename [-h] <-d TEST_DIR> <-t TEST_NAME>\n";
	exit(1);
}

my %opt;

getopts("hd:t:", \%opt) or usage();
usage() if $opt{h} || !defined $opt{d} || !defined $opt{t};

if (!-d "$opt{d}") {
	print STDERR "Test output directory does not exist ($opt{d})\n";
	exit(1);
}

my $testdir = $opt{d};
my $testname = $opt{t};

if (!-f "$testdir/$testname.run.0") {
	print STDERR "No $testname runs\n";
	exit(1);
}

my $user_hz = 100;

# track times for total
my %real = ("sum" => 0, "count" => 0, "min" => -1, "max" => 0);
my %sys = %real;
my %user = %real;
my %io = %real;

my @totalsa = (\%real, \%sys, \%user, \%io);

sub updateStats {
	my $total = shift;
	my $time = shift;
	$total->{"sum"} += $time;
	$total->{"count"}++;
	$total->{"min"} = $time if ($time < $total->{"min"} || $total->{"min"} == -1);
	$total->{"max"} = $time if ($time > $total->{"max"});
}

foreach $run (<$testdir/$testname.run.*>) {
	#print STDERR "run: $run\n";
	open(R, "<$run") || die;
	my $total_io = 0;
	my $total_before;
	my $state = 0;
	while(<R>) {
		my $line = $_;
		if ($line =~ m/^total-before/) {
			$total_before = $line;
		} elsif ($line =~ m/^total-after/) {
			my $total_after = $line;
			# there is actually one more number in the cpu line. what is it?
			$total_before =~ m/cpu\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)/;
			my $user = $1 + $2;
			my $sys = $3;
			my $io = $4 + $5 + $6 + $7;

			$total_after =~ m/cpu\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)/;
			$user = ($1 + $2 - $user) / $user_hz;
			$sys = ($3 - $sys) / $user_hz;
			$io = ($4 + $5 + $6 + $7 - $io) / $user_hz;
			my $real = $user + $sys + $io;

			updateStats(\%user, $user);
			updateStats(\%sys, $sys);
			updateStats(\%io, $io);
			updateStats(\%real, $real);
		}
	}
	close(R);
}

foreach $total (@totalsa) {
	my $avg = 0;
	$avg = $total->{"sum"} / $total->{"count"} if ($total->{"count"} != 0);
	printf "%.2f %.2f %.2f  ", $avg, $total->{"min"}, $total->{"max"};
}
print "\n";
