#!/bin/bash

function do_imap () {
	LD_LIBRARY_PATH=$FSTITCHDIR/obj/kernel/lib:$LD_LIBRARY_PATH IMAPD=$IMAPD MAILPATH=$MNT $FSTITCHDIR/bench/imap.expect > $OUTDIR/$T.imap.$N
}

function test () {
	ktime imap do_imap
	ktime sync fsync $FSTITCHDIR $MNT;
}

function run () {
	try $BENCHDIR/init -h $HOST -d $DISKCACHE -f $FS -c $CMODE $CRASHSIM -a start -k
	prepare_postinit  $T $N $OUTDIR $HOST
	ktime total test
	try $BENCHDIR/init -h $HOST -d $DISKCACHE -f $FS -c $CMODE $CRASHSIM -a stop
}

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
FSTITCHDIR="$BENCHDIR/.."
OUTDIR="$FSTITCHDIR/test"
load_config "$OUTDIR"
T=imap
[ -n "$TESTNAME" ] && T="${T}-$TESTNAME"
N=`get_test_num $OUTDIR/$T`

case "$ACMODE" in
	fsync)   IMAPD=/home/fsttich/ouwimap/imapd/imapd;;
	linear)  IMAPD=/home/fsttich/juwimap/imapd/imapd;;
	patchgroup) IMAPD=/home/fsttich/puwimap/imapd/imapd;;
	*) echo "Unsupported ACMODE $ACMODE" 1>&2; exit 1;;
esac

if [ $# -ne 0 ]; then
	echo "Usage: `basename "$0"`" 1>&2
	exit 1;
fi

build $T $N $FSTITCHDIR $HOST
try $BENCHDIR/init -h $HOST -d $DISKCACHE -f $FS -c $CMODE -a start
[ -f /proc/kfstitchd_debug ] && cat /proc/kfstitchd_debug > /dev/null &
try sh -c "gunzip -c $FSTITCHDIR/bench/mailbox.src.gz > $MNT/mailbox.src"
try rm -f $MNT/mailbox.dst
try $BENCHDIR/init -h $HOST -d $DISKCACHE -f $FS -c $CMODE -a stop
try sync

log_kernel $T $N $OUTDIR $HOST
run 2>&1 | tee $OUTDIR/$T.run.$N
finish $T $N $FSTITCHDIR $OUTDIR $HOST $CRASHSIM
