#!/usr/bin/expect -f
# Move messages from one mailbox to another

set imapd $env(IMAPD)
set mailpath $env(MAILPATH)
# doesn't work with >1 arg:
#set imapd [lrange $argv 0 1]
#set mailpath [lrange $argv 1 2]

set nmsgs 100
set cmdn 1

if {![file exists $imapd]} {
	puts "Error: file \"$imapd\" does not exist"
	puts "Usage: $argv0 <imapd_file>"
	exit 1
}

spawn $imapd
expect -re "\\* PREAUTH .*\r\r"

send "$cmdn select $mailpath/mailbox.src\r"
expect -re "\\* $nmsgs EXISTS\r\r.*$cmdn OK .READ-WRITE. SELECT completed\r\r"
incr cmdn

send "$cmdn create $mailpath/mailbox.dst\n"
expect "$cmdn OK CREATE completed\r\r"
incr cmdn

for {set i 1} {$i<=$nmsgs} {incr i} {
	send "$cmdn copy $i $mailpath/mailbox.dst\r"
	expect "$cmdn OK COPY completed\r\r"
	incr cmdn

	send "$cmdn store $i +flags (\\Deleted)\r"
#	expect -re "\\* $i FETCH \(FLAGS \(.*\)\)\r\r$cmdn OK STORE completed\r\r"
	expect -re ".*$cmdn OK STORE completed\r\r"
	incr cmdn
}

send "$cmdn expunge\r"
expect -re ".*$cmdn OK Expunged $nmsgs messages\r\r"
incr cmdn

send "$cmdn close\r"
expect "$cmdn OK CLOSE completed"
incr cmdn

send "$cmdn logout\r"
expect "$cmdn OK LOGOUT completed"
expect eof
