#!/bin/bash

TYPE=${TYPE:-ext3}
DEV=${DEV:-/dev/sdb1}
MNT=/mnt/test

function try () {
	echo "+ $@"
	$@ || exit 1
}

if [ $# -ne 1 ]; then
	echo "Usage: `basename "$0"` <start|stop>" 1>&2
	exit 1
fi

if [ "$1" == "start" ]; then
	sync
	try sudo mkfs.$TYPE $DEV
	try sudo mount -t $TYPE /dev/sdb1 $MNT
	try sudo chmod 777 $MNT
elif [ "$1" == "stop" ]; then
	try sudo umount $MNT
else
	echo "Unknown action \"$1\"" 1>&2
	exit 1
fi
