#!/bin/bash

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."
TESTS="tests"
OUTDIR="test"

function usage () {
	echo "About: create a new kudos test directory"
	echo "Usage: `basename "$0"` [-f INITFS] [-c INITCONSISTENCYMODE] [-h INITHOST] [-n NAME]"
}

FS=ext2
CMODE=
HOST=kudos
NAME=

while getopts "f:c:h:n:" flag; do
	case "$flag" in
		f) FS="$OPTARG";;
		c) CMODE="$OPTARG";;
		h) HOST="$OPTARG";;
		n) NAME="$OPTARG";;
		\?) usage 1>&2; exit 1;;
		*) usage 1>&2; exit 1;;
	esac
done

CMODE="`canonicalize_cmode $HOST $FS $CMODE`"

if ! supported_host_fs "${HOST}-${FS}-${CMODE}"; then
	echo "Unsupported host-filesystem-cmode \"${HOST}-${FS}-${CMODE}\"" 1>&2
	exit 1
fi

NEWTEST=`date --iso=seconds`

cd $KUDOSDIR
[ -d $TESTS ] || try mkdir $TESTS
try mkdir $TESTS/$NEWTEST
try rm -f $OUTDIR
try ln -s $TESTS/$NEWTEST $OUTDIR

echo "$HOST" > $OUTDIR/host
echo "$FS" > $OUTDIR/fs
echo "$CMODE" > $OUTDIR/consistency_mode
echo "$NAME" > $OUTDIR/name
uname -a > $OUTDIR/uname
svnversion . > $OUTDIR/svnversion
svn diff > $OUTDIR/diff
