#!/bin/bash

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."
TESTS="tests"
OUTDIR="test"

if [ $# -lt 1 ] || [ $# -gt 2 ] || ([ $# -eq 1 ] && [ "$1" == "-h" ]); then
	echo "About: create a new kudos test directory" 1>&2
	echo "Usage: `basename "$0"` <INITFS> [NAME]" 1>&2
	exit 1
fi
FS="$1"
NAME=
[ $# -eq 2 ] && NAME="$2"

NEWTEST=`date --iso=seconds`

cd $KUDOSDIR
[ -d $TESTS ] || try mkdir $TESTS
try mkdir $TESTS/$NEWTEST
try rm -f $OUTDIR
try ln -s $TESTS/$NEWTEST $OUTDIR

echo "$FS" > $OUTDIR/fs
echo "$NAME" > $OUTDIR/name
uname -a > $OUTDIR/uname
svnversion . > $OUTDIR/svnversion
svn diff > $OUTDIR/diff
