#!/bin/bash

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."

function usage () {
	echo "About: Generate io plot for a given test"
	echo "Usage: `basename "$0"` <-t TESTNAME> <-o OUTDIR> [-k time|rev]"
}

KEY=time
while getopts "t:o:k:" flag; do
	case "$flag" in
		t) TESTNAME="$OPTARG";;
		o) OUTDIR="$OPTARG";;
		k) KEY="$OPTARG";;
		/?) usage 1>&2; exit 1;;
		*) usage 1>&2; exit 1;;
	esac
done

if [ -z "$TESTNAME" ] || [ -z "$OUTDIR" ]; then
	usage 1>&2
	exit 1
fi

if [ "$KEY" != "rev" ] && [ "$KEY" != "time" ]; then
	echo "Illegal key \"$KEY\"" 1>&2
	usage 1>&2
	exit 1
fi

if [ ! -d "$OUTDIR" ]; then
	echo "OUTDIR $OUTDIR does not exist" 1>&2
	exit 1
fi

DATA=`mktemp plot_io.XXXXXX` || exit 1
trap "rm -f $DATA" EXIT

for test in `ls $KUDOSDIR/tests/`; do
	if [ "`cat $KUDOSDIR/tests/$test/host`" != "kudos" ] || [ "`cat $KUDOSDIR/tests/$test/diskcache`" != "safe" ] || [ "`cat $KUDOSDIR/tests/$test/fs`" != "ext2" ] || [ "`cat $KUDOSDIR/tests/$test/consistency_mode`" != "su" ] || [ "`cat $KUDOSDIR/tests/$test/app_consistency_mode`" != "opgroup" ]; then continue; fi

	LINE="`$BENCHDIR/ex_io -d $KUDOSDIR/tests/$test -t $TESTNAME`"
	[ -n "$LINE" ] || continue
	if [ "$KEY" == "time" ] ; then
		echo -n "$test"
	elif [ "$KEY" == "rev" ]; then
		echo -n "`cat $KUDOSDIR/tests/$test/svnversion | sed -r 's/:[0-9]+//;s/M$//'`"
	fi
	echo "  $LINE"
done | sort > $DATA

if [ "$KEY" == "time" ]; then
	XAXIS="set xlabel \"Test (time)\"; set xdata time; set timefmt \"%Y-%m-%dT%H:%M:%S\""
elif [ "$KEY" == "rev" ]; then
	XAXIS="set xlabel \"Test (rev)\""
fi

gnuplot << EOF
set terminal png
#set key above # above is only in gnuplot > 4.0, but it will look better
set key outside
set grid
$XAXIS

set title "$TESTNAME I/O"
set ylabel "# requests"
set yrange [0:]
set y2tics border
set y2label "kBs"
set y2range [0:]
set output "$OUTDIR/io_${TESTNAME}.png"
plot \
	"$DATA" using 1:2:3:4 with yerrorlines title "write requests", \
	"$DATA" using 1:5:6:7 with yerrorlines axes x1y2 title "write kBs", \
	"$DATA" using 1:14:15:16 with yerrorlines title "read requests", \
	"$DATA" using 1:17:18:19 with yerrorlines axes x1y2 title "read kBs"
EOF


gnuplot << EOF
set terminal png
#set key above # above is only in gnuplot > 4.0, but it will look better
set key outside
set grid
$XAXIS

set title "$TESTNAME I/O for sectors written more than once"
set ylabel "# sectors"
set yrange [0:]
set y2tics border
set y2label "# writes"
set y2range [0:]
set output "$OUTDIR/io_multi_${TESTNAME}.png"
plot \
	"$DATA" using 1:8:9:10 with yerrorlines title "# sectors", \
	"$DATA" using 1:11:12:13 with yerrorlines axes x1y2 title "# writes"
EOF
