#!/bin/bash

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."

function usage () {
	echo "About: Generate time plot for a given test"
	echo "Usage: `basename "$0"` <-t TESTNAME> <-o OUTDIR> [-k time|rev]"
}

KEY=time
while getopts "t:o:k:" flag; do
	case "$flag" in
		t) TESTNAME="$OPTARG";;
		o) OUTDIR="$OPTARG";;
		k) KEY="$OPTARG";;
		/?) usage 1>&2; exit 1;;
		*) usage 1>&2; exit 1;;
	esac
done

if [ -z "$TESTNAME" ] || [ -z "$OUTDIR" ]; then
	usage 1>&2
	exit 1
fi

if [ "$KEY" != "rev" ] && [ "$KEY" != "time" ]; then
	echo "Illegal key \"$KEY\"" 1>&2
	usage 1>&2
	exit 1
fi

if [ ! -d "$OUTDIR" ]; then
	echo "OUTDIR $OUTDIR does not exist" 1>&2
	exit 1
fi

DATA=`mktemp plot_time.XXXXXX` || exit 1
trap "rm -f $DATA" EXIT

for test in `ls $KUDOSDIR/tests/`; do
	[ "`cat $KUDOSDIR/tests/$test/host`" == "kudos" ] || continue
	LINE="`$BENCHDIR/ex_time -d $KUDOSDIR/tests/$test -t $TESTNAME`"
	[ -n "$LINE" ] || continue
	if [ "$KEY" == "time" ] ; then
		echo -n "$test"
	elif [ "$KEY" == "rev" ]; then
		echo -n "`cat $KUDOSDIR/tests/$test/svnversion |sed 's/:\d+//;s/M$//'`"
	fi
	echo "  $LINE"
done > $DATA

if [ "$KEY" == "time" ]; then
	XAXIS="set xlabel \"Test (time)\"; set xdata time; set timefmt \"%Y-%m-%dT%H:%M:%S\""
elif [ "$KEY" == "rev" ]; then
	XAXIS="set xlabel \"Test (rev)\""
fi

gnuplot << EOF
set terminal png
set key above
set grid
$XAXIS

set title "$TESTNAME time"
set ylabel "Time (seconds)"
set output "$OUTDIR/time_${TESTNAME}.png"
plot [:] [0:] \
	"$DATA" using 1:2:3:4 with yerrorlines title "real", \
	"$DATA" using 1:5:6:7 with yerrorlines title "sys", \
	"$DATA" using 1:11:12:13 with yerrorlines title "io", \
	"$DATA" using 1:8:9:10 with yerrorlines title "user"
EOF
