#!/bin/bash

function run_postmark () {
	# TODO: 500 kB is way too small, but we crash with larger (eg 1 MB)
	ktime postmark $BENCHDIR/postmark-1_5 <<- EOF
		set location $MNT
		set number 500
		set size 500 500000
		set write 4096
		set read 4096
		run
	EOF
	ktime sync fsync $KUDOSDIR $MNT
}

function run () {
	try $BENCHDIR/init -f $FS -c $CMODE -h $HOST -a start
	prepare_postinit $T $N $OUTDIR $HOST
	ktime total run_postmark
	try $BENCHDIR/init -f $FS -c $CMODE -h $HOST -a stop
}

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."
OUTDIR="$KUDOSDIR/test"
HOST=`cat "$OUTDIR/host"`
FS=`cat "$OUTDIR/fs"`
CMODE=`cat "$OUTDIR/consistency_mode"`
T=postmark
[ -n "$TESTNAME" ] && T="${T}-$TESTNAME"
N=`get_test_num $OUTDIR/$T`

if [ $# -ne 0 ]; then
	echo "Usage: `basename "$0"`" 1>&2
	exit 1;
fi

build $T $N $KUDOSDIR $HOST
try gcc -O2 $BENCHDIR/postmark-1_5.c -o $BENCHDIR/postmark-1_5
try sync

log_kernel $T $N $OUTDIR $HOST
run 2>&1 | tee $OUTDIR/$T.run.$N
finish $T $N $KUDOSDIR $OUTDIR $HOST
