#!/bin/bash

function test () {
	ktime rm rm -rf $MNT/$TAROUT
	ktime sync fsync $KUDOSDIR $MNT
}

function run () {
	try $BENCHDIR/init -f $FS -c $CMODE -h $HOST -a start -k
	[ ! -d $MNT/$TAROUT ] && echo "$MNT/$TAROUT does not exist" && exit 1
	prepare_postinit $T $N $OUTDIR $HOST
	ktime total test
	try $BENCHDIR/init -f $FS -c $CMODE -h $HOST -a stop
}

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."
OUTDIR="$KUDOSDIR/test"
HOST=`cat "$OUTDIR/host"`
FS=`cat "$OUTDIR/fs"`
CMODE=`cat "$OUTDIR/consistency_mode"`
T=rm
[ -n "$TESTNAME" ] && T="${T}-$TESTNAME"
N=`get_test_num $OUTDIR/$T`
TAROUT=linux-2.6.15

if [ $# -ne 0 ]; then
	echo "Usage: `basename "$0"`" 1>&2
	exit 1;
fi

build $T $N $KUDOSDIR $HOST

log_kernel $T $N $OUTDIR $HOST
run 2>&1 | tee $OUTDIR/$T.run.$N
finish $T $N $KUDOSDIR $OUTDIR $HOST
