#!/bin/bash

function run () {
	try $BENCHDIR/init -f $FS -h $HOST -a start -k
	[ ! -d $MNT/$TAROUT ] && echo "$MNT/$TAROUT does not exist" && exit 1
	start_kdb_log $T $N $OUTDIR $HOST
	time (echo + rm; time rm -rf $MNT/$TAROUT;
	      echo + sync; time fsync $KUDOSDIR $MNT;
	      echo + total)
	try $BENCHDIR/init -f $FS -h $HOST -a stop
}

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."
OUTDIR="$KUDOSDIR/test"
HOST=`cat "$OUTDIR/host"`
FS=`cat "$OUTDIR/fs"`
T=rm
[ -n "$TESTNAME" ] && T="${T}-$TESTNAME"
N=`get_test_num $OUTDIR/$T`
TAROUT=linux-2.6.15

if [ $# -ne 0 ]; then
	echo "Usage: `basename "$0"`" 1>&2
	exit 1;
fi

prepare $T $N $KUDOSDIR $OUTDIR $HOST
run 2>&1 | tee $OUTDIR/$T.run.$N
finish $T $N $KUDOSDIR $OUTDIR $HOST
