#!/bin/bash

function test () {
	ktime rm rm -rf $MNT/$TAROUT
	ktime sync fsync $FSTITCHDIR $MNT
}

function run () {
	# Create the file system
	try $BENCHDIR/init -f $FS -c $CMODE -h $HOST -a start
	try $BENCHDIR/init -f $FS -c $CMODE -h $HOST -a stop

	# Untar using Linux ext2
	try $BENCHDIR/init -f ext2 -c none -h linux -a start -k
	try tar -C $MNT/ -xf $TARFILE
	try $BENCHDIR/init -f ext2 -c none -h linux -a stop

	# Remove using the specified parameters
	try $BENCHDIR/init -f $FS -c $CMODE -h $HOST $CRASHSIM -a start -k
	[ ! -d $MNT/$TAROUT ] && echo "$MNT/$TAROUT does not exist" && exit 1
	prepare_postinit $T $N $OUTDIR $HOST
	ktime total test
	try $BENCHDIR/init -f $FS -c $CMODE -h $HOST $CRASHSIM -a stop
}

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
FSTITCHDIR="$BENCHDIR/.."
OUTDIR="$FSTITCHDIR/test"
HOST=`cat "$OUTDIR/host"`
FS=`cat "$OUTDIR/fs"`
CMODE=`cat "$OUTDIR/consistency_mode"`
T=rm
[ -n "$TESTNAME" ] && T="${T}-$TESTNAME"
N=`get_test_num $OUTDIR/$T`
TARFILE=linux-2.6.15.tar
TAROUT=linux-2.6.15

if [ $# -ne 0 ]; then
	echo "Usage: `basename "$0"`" 1>&2
	exit 1;
fi

prepare $T $N $FSTITCHDIR $OUTDIR $HOST
run 2>&1 | tee $OUTDIR/$T.run.$N
finish $T $N $FSTITCHDIR $OUTDIR $HOST $CRASHSIM
