#!/bin/bash
# Run the imap test

if [ $# -ne 3 ]; then
	echo "Usage: $0 <imapd_file> <mailpath> <fscorepath>"
	exit 1
fi

IMAPD=$1
MAILPATH=$2
FSTITCHPATH=$3

rm -f $MAILPATH/mailbox.src
cp mailbox.src.gz $MAILPATH || exit 1
gunzip $MAILPATH/mailbox.src.gz
rm -f $MAILPATH/mailbox.dst

sync
if [ "$FSTITCHPATH" != "" ]; then
	$FSTITCHPATH/obj/util/fsync $MAILPATH
fi

echo -n "Press return to run test: "
read x

IMAPD=$IMAPD MAILPATH=$MAILPATH ./imap.expect
