#!/bin/bash

function set_nrb () {
	sed -i "s/^#define CHDESC_NRB .$/#define CHDESC_NRB $1/" kfs/chdesc.h
}

function set_overlap_merge () {
	sed -i "s/^#define CHDESC_BYTE_MERGE_OVERLAP .$/#define CHDESC_BYTE_MERGE_OVERLAP $1/;s/^#define CHDESC_BIT_MERGE_OVERLAP .$/#define CHDESC_BIT_MERGE_OVERLAP $1/" kfs/chdesc.c
}

if [ $# -ne 1 ] && [ $# -ne 2 ]; then
	echo "About: Run kbench with various optimizations enabled and disabled" 1>&2
	echo "Usage: `basename \"$0\"` <fs> <NRUNS=1>" 1>&2
	exit 1
fi

REAL_USER="`whoami`"
FS="$1"
[ $# -ge 2 ] && NRUNS=$2 || NRUNS=1

make || exit 1

echo "Hard + Overlap" | tee -a time.log
set_nrb 1
set_overlap_merge 1
sudo bench/kbench.sh $REAL_USER $FS $NRUNS

echo "Hard" | tee -a time.log
set_overlap_merge 0
sudo bench/kbench.sh $REAL_USER $FS $NRUNS

echo "Overlap" | tee -a time.log
set_nrb 0
set_overlap_merge 1
sudo bench/kbench.sh $REAL_USER $FS $NRUNS

echo "None" | tee -a time.log
set_overlap_merge 0
sudo bench/kbench.sh $REAL_USER $FS $NRUNS

echo "Reenabling optimizations"
set_nrb 1
set_overlap_merge 1
