#!/bin/bash

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
FSTITCHDIR="$BENCHDIR/.."
OUTDIR="$FSTITCHDIR/test"
HOST="`cat $FSTITCHDIR/test/host`"
FS="`cat $FSTITCHDIR/test/fs`"

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
	echo "About: run a single test (multiple times and for memory accounting)"
	echo "Usage: `basename "$0"` <program> [NRUNS]" 1>&2
	exit 1;
fi
TESTNAME="$1"
NRUNS=3
[ $# -eq 2 ] && NRUNS="$2"

$BENCHDIR/multi $NRUNS "$TESTNAME"
if [ "$HOST" == "fstitch" ] || [ "$HOST" == "uu" ]; then
	if grep -v linux- $OUTDIR/fs; then
		accounting_on; TESTNAME=mem "$TESTNAME"; accounting_restore
	fi
fi
