#!/bin/bash

function run () {
	try $BENCHDIR/init -f $FS -h $HOST -a start
	prepare_postinit  $T $N $OUTDIR $HOST
	time (echo + split; dd if=/dev/zero bs=$FILESZ count=$NFILE | \
	                    time split -b $FILESZ - $MNT/file_;
	      echo + sync; time fsync $KUDOSDIR $MNT;
	      echo + total)
	try $BENCHDIR/init -f $FS -h $HOST -a stop
}

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."
OUTDIR="$KUDOSDIR/test"
HOST=`cat "$OUTDIR/host"`
FS=`cat "$OUTDIR/fs"`
T=split
[ -n "$TESTNAME" ] && T="${T}-$TESTNAME"
N=`get_test_num $OUTDIR/$T`
FILESZ=98304
NFILE=512

if [ $# -ne 0 ]; then
	echo "Usage: `basename "$0"`" 1>&2
	exit 1;
fi

prepare $T $N $KUDOSDIR $OUTDIR $HOST
run 2>&1 | tee $OUTDIR/$T.run.$N
finish $T $N $KUDOSDIR $OUTDIR $HOST
