#!/bin/bash

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."

TESTS="tar rm postmark"

function usage () {
	echo "About: generate all tables"
	echo "Usage: `basename "$0"` <-o OUTDIR>"
}

while getopts "o:" flag; do
	case "$flag" in
		o) OUTDIR="$OPTARG";;
		/?) usage 1>&2; exit 1;;
		*) usage 1>&2; exit 1;;
	esac
done

for TESTNAME in $TESTS; do
	try $BENCHDIR/table_time -t $TESTNAME -o $OUTDIR
done
