#!/bin/bash

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."

TESTS="tar rm postmark"

function usage () {
	echo "About: generate all tables"
	echo "Usage: `basename "$0"` <-o OUTDIR>"
}

while getopts "o:" flag; do
	case "$flag" in
		o) OUTDIR="$OPTARG";;
		/?) usage 1>&2; exit 1;;
		*) usage 1>&2; exit 1;;
	esac
done

if [ -z "$OUTDIR" ]; then
	usage 1>&2
	exit 1
fi
if [ ! -d "$OUTDIR" ]; then
	echo "OUTDIR $OUTDIR does not exist" 1>&2
	exit 1
fi

for TESTNAME in $TESTS; do
	try $BENCHDIR/table -m time -t $TESTNAME -o $OUTDIR
	try $BENCHDIR/table -m space -t $TESTNAME -o $OUTDIR
	try $BENCHDIR/table -m io -t $TESTNAME -o $OUTDIR
done
