#!/bin/bash

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."

function usage () {
	echo "About: Generate time table for a given test"
	echo "Usage: `basename "$0"` <-t TESTNAME> <-o OUTDIR>"
}

KEY=time
while getopts "t:o:" flag; do
	case "$flag" in
		t) TESTNAME="$OPTARG";;
		o) OUTDIR="$OPTARG";;
		/?) usage 1>&2; exit 1;;
		*) usage 1>&2; exit 1;;
	esac
done

if [ -z "$OUTDIR" ]; then
	usage 1>&2
	exit 1
fi
if [ ! -d "$OUTDIR" ]; then
	echo "OUTDIR $OUTDIR does not exist" 1>&2
	exit 1
fi

function most_recent_test () {
	HOST="$1"
	FS="$2"
	REV=0
	MR=
	for test in `ls -t $KUDOSDIR/tests/`; do
		DIR="$KUDOSDIR/tests/$test"
		REVN=`cat $DIR/svnversion | sed -r 's/:[0-9]+//;s/M$//'`
		[ $REVN -le $REV ] && continue
		if [ "`cat $DIR/host`" == "$HOST" ] && [ "`cat $DIR/fs`" == "$FS" ]; then
			MR="$test"
			REV=$REVN
		fi
	done
	echo "$MR"
}

ARRAYNAME="space_${TESTNAME}_data"
JSFILE="$OUTDIR/space_${TESTNAME}.js"

echo "var $ARRAYNAME = new Array();" > $JSFILE
I=0
for sys in "kudos ext2"; do
	HOST=`echo "$sys" | awk '{print $1}'`
	FS=`echo "$sys" | awk '{print $2}'`
	RECENT="`most_recent_test $HOST $FS`"

	[ -z "$RECENT" ] && echo "No data for $HOST $FS" && continue

	echo "Most recent for $HOST $FS is $RECENT"
	DATA="`$BENCHDIR/ex_space -d $KUDOSDIR/tests/$RECENT -t $TESTNAME | sed 's/\([0-9]\) /\1, /g;s/, *$//'`"
	echo "${ARRAYNAME}[$I] = new Array(\"$HOST\", \"$FS\", ${DATA});" >> $JSFILE
	I=$((I+1))
done
