#!/bin/bash

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."

function usage () {
	echo "About: Generate javascript table data for a given test and measurement"
	echo "Usage: `basename "$0"` <-m MEASUREMENT> <-t TESTNAME> <-o OUTDIR>"
	echo "       where MEASUREMENT is one of time, space, or io"
}

while getopts "m:t:o:" flag; do
	case "$flag" in
		m) MEASUREMENT="$OPTARG";;
		t) TESTNAME="$OPTARG";;
		o) OUTDIR="$OPTARG";;
		/?) usage 1>&2; exit 1;;
		*) usage 1>&2; exit 1;;
	esac
done

if [ -z "$MEASUREMENT" ]; then
	usage 1>&2
	exit 1
fi

if [ -z "$OUTDIR" ]; then
	usage 1>&2
	exit 1
fi
if [ ! -d "$OUTDIR" ]; then
	echo "OUTDIR $OUTDIR does not exist" 1>&2
	exit 1
fi

function most_recent_test () {
	HOST="$1"
	FS="$2"
	CMODE="$3"
	REV=0
	MR=
	for test in `ls -t $KUDOSDIR/tests/`; do
		DIR="$KUDOSDIR/tests/$test"
		REVN=`cat $DIR/svnversion | sed -r 's/:[0-9]+//;s/M$//'`
		[ $REVN -le $REV ] && continue
		if [ "`cat $DIR/host`" == "$HOST" ] && [ "`cat $DIR/fs`" == "$FS" ] && [ "`cat $DIR/consistency_mode`" == "$CMODE" ]; then
			MR="$test"
			REV=$REVN
		fi
	done
	echo "$MR"
}

ARRAYNAME="${MEASUREMENT}_${TESTNAME}_data"
JSFILE="$OUTDIR/${MEASUREMENT}_${TESTNAME}.js"

echo "var $ARRAYNAME = new Array();" > $JSFILE
I=0
for sys in "kudos ext2 su" "kudos ext2 meta" "kudos ext2 full" "linux ext2 none" "linux ext3 ordered" "linux ext3 journal"; do
	HOST=`echo "$sys" | awk '{print $1}'`
	FS=`echo "$sys" | awk '{print $2}'`
	CMODE=`echo "$sys" | awk '{print $3}'`
	RECENT="`most_recent_test $HOST $FS $CMODE`"

	[ -z "$RECENT" ] && echo "No data for $HOST $FS $CMODE" && continue

	echo "Most recent for $HOST $FS $CMODE is $RECENT"
	DATA="`$BENCHDIR/ex_${MEASUREMENT} -d $KUDOSDIR/tests/$RECENT -t $TESTNAME | sed 's/\([0-9]\) /\1, /g;s/, *$//'`"
	[ -z "$DATA" ] && echo "No data for $HOST $FS $CMODE" && continue
	echo "${ARRAYNAME}[$I] = new Array(\"$HOST\", \"$FS\", \"$CMODE\", ${DATA});" >> $JSFILE
	I=$((I+1))
done
