#!/bin/bash

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
FSTITCHDIR="$BENCHDIR/.."

function usage () {
	echo "About: Generate javascript table data for a given test and measurement"
	echo "Usage: `basename "$0"` <-m MEASUREMENT> <-t TESTNAME> <-o OUTDIR>"
	echo "       where MEASUREMENT is one of time, space, or io"
}

while getopts "m:t:o:" flag; do
	case "$flag" in
		m) MEASUREMENT="$OPTARG";;
		t) TESTNAME="$OPTARG";;
		o) OUTDIR="$OPTARG";;
		/?) usage 1>&2; exit 1;;
		*) usage 1>&2; exit 1;;
	esac
done

if [ -z "$MEASUREMENT" ]; then
	usage 1>&2
	exit 1
fi

if [ -z "$OUTDIR" ]; then
	usage 1>&2
	exit 1
fi
if [ ! -d "$OUTDIR" ]; then
	echo "OUTDIR $OUTDIR does not exist" 1>&2
	exit 1
fi

function most_recent_test () {
	REV=0
	MR=
	for test in `ls -t $FSTITCHDIR/tests/`; do
		DIR="$FSTITCHDIR/tests/$test"
		REVN=`cat $DIR/svnversion | sed -r 's/:[0-9]+//;s/M$//'`
		[ $REVN -le $REV ] && continue
		if [ "`cat $DIR/host`" == "$HOST" ] && [ "`cat $FSTITCHDIR/tests/$test/diskcache`" == "$DISKCACHE" ] && [ "`cat $DIR/fs`" == "$FS" ] && [ "`cat $DIR/consistency_mode`" == "$CMODE" ] && [ "`cat $FSTITCHDIR/tests/$test/app_consistency_mode`" == "$ACMODE" ] && [ -f $DIR/$TESTNAME.run.0 ]; then
			MR="$test"
			REV=$REVN
		fi
	done
	echo "$MR"
}

ARRAYNAME="${MEASUREMENT}_${TESTNAME}_data"
JSFILE="$OUTDIR/${MEASUREMENT}_${TESTNAME}.js"

echo "var $ARRAYNAME = new Array();" > $JSFILE
I=0
for sys in \
	"fstitch safe ext2 su patchgroup" \
	"fstitch safe ext2 meta patchgroup" \
	"fstitch safe ext2 full patchgroup" \
	"fstitch safe ext2 none patchgroup" \
	"fstitch safe ext2 full linearom" \
	"fstitch safe ext2 full linear" \
	"linux unsafe ext2 none fsync" \
	"linux unsafe ext3 ordered fsync" \
	"linux unsafe ext3 journal fsync" \
	"linux unsafe ext3 ordered linearom" \
	"linux unsafe ext3 journal linearom" \
	"linux unsafe ext3 journal linear" \
	"linux safe ext2 none fsync" \
	"linux safe ext3 ordered fsync" \
	"linux safe ext3 journal fsync" \
	"linux safe ext3 ordered linearom" \
	"linux safe ext3 journal linearom" \
	"linux safe ext3 journal linear"
do
	HOST=`echo "$sys" | awk '{print $1}'`
	DISKCACHE=`echo "$sys" | awk '{print $2}'`
	FS=`echo "$sys" | awk '{print $3}'`
	CMODE=`echo "$sys" | awk '{print $4}'`
	ACMODE=`echo "$sys" | awk '{print $5}'`
	RECENT="`most_recent_test`"

	if [ -z "$RECENT" ]; then
		#echo "No data for $HOST $DISKCACHE $FS $CMODE $ACMODE $TESTNAME"
		continue
	fi
	REV="`cat $FSTITCHDIR/tests/$RECENT/svnversion`"

	#echo "Most recent for $HOST $DISKCACHE $FS $CMODE $ACMODE $TESTNAME is $RECENT"
	DATA="`$BENCHDIR/ex_${MEASUREMENT} -d $FSTITCHDIR/tests/$RECENT -t $TESTNAME | sed 's/\([0-9]\) /\1, /g;s/, *$//'`"
	if [ -z "$DATA" ]; then
		#echo "No data for $HOST $DISKCACHE $FS $CMODE $ACMODE $TESTNAME"
		continue
	fi
	echo "${ARRAYNAME}[$I] = new Array(\"$HOST\", \"$DISKCACHE\", \"$FS\", \"$CMODE\", \"$ACMODE\", \"$REV\", ${DATA});" >> $JSFILE
	I=$((I+1))
done
