#!/bin/bash

function run () {
	try cat $TARFILE >/dev/null
	try $BENCHDIR/init -f $FS -h $HOST -a start
	time (echo + tar; time tar -C $MNT/ -xf $TARFILE;
	      echo + sync; time fsync $KUDOSDIR $MNT;
	      echo + total)
	try $BENCHDIR/init -f $FS -h $HOST -a stop
}

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."
OUTDIR="$KUDOSDIR/test"
HOST=`cat "$OUTDIR/host"`
FS=`cat "$OUTDIR/fs"`
T=tar
[ -n "$TESTNAME" ] && T="${T}-$TESTNAME"
N=`get_test_num $OUTDIR/$T`
TARFILE=linux-2.6.15.tar

if [ $# -ne 0 ]; then
	echo "Usage: `basename "$0"`" 1>&2
	exit 1;
fi

prepare $T $N $KUDOSDIR $OUTDIR $HOST
run 2>&1 | tee $OUTDIR/$T.run.$N
