#!/bin/bash

function test () {
	ktime tar tar -C $MNT/ -xf $TARFILE
	ktime sync fsync $KUDOSDIR $MNT;
}

function run () {
	try $BENCHDIR/init -h $HOST -d $DISKCACHE -f $FS -c $CMODE $CRASHSIM -a start
	prepare_postinit  $T $N $OUTDIR $HOST
	ktime total test
	try $BENCHDIR/init -h $HOST -d $DISKCACHE -f $FS -c $CMODE $CRASHSIM -a stop
}

BENCHDIR="`dirname "$0"`"
. $BENCHDIR/common
KUDOSDIR="$BENCHDIR/.."
OUTDIR="$KUDOSDIR/test"
load_config "$OUTDIR"
T=tar
[ -n "$TESTNAME" ] && T="${T}-$TESTNAME"
N=`get_test_num $OUTDIR/$T`
TARFILE=linux-2.6.15.tar

if [ $# -ne 0 ]; then
	echo "Usage: `basename "$0"`" 1>&2
	exit 1;
fi

build $T $N $KUDOSDIR $HOST
try cat $TARFILE >/dev/null

log_kernel $T $N $OUTDIR $HOST
run 2>&1 | tee $OUTDIR/$T.run.$N
finish $T $N $KUDOSDIR $OUTDIR $HOST $CRASHSIM
